name: Run Makefile

on:
  push:
  pull_request:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid

      - name: Compile
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: iPod
          path: packages/*